name: nift
version: '1.20'
summary: website generator
license: MIT
description: |
  `snap install nift --classic`
  
  Nift (aka nsm) is a cross-platform open source 
  command-line website generator. See https://nift.cc.

confinement: classic
base: core18

parts:
  nsm:
    plugin: make
    source-type: zip
    source: https://github.com/nifty-site-manager/nsm-snap/raw/master/nsm.zip
    build-packages:
    - g++
    stage-packages:
    - git-core

apps:
  nift:
    command: nift
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
  nsm:
    command: nsm
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      DISABLE_WAYLAND: '1'
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
